In [1]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [2]:
# 0으로 초기화된 배열
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
#  빈값으로 만들어진 배열
arr = np.empty((4,3))
print(arr)

[[9.16955015e-312 3.16202013e-322 0.00000000e+000]
 [0.00000000e+000 1.18831764e-312 2.58403511e-057]
 [1.85364069e-051 2.44598765e-056 1.23185286e+165]
 [1.20963121e+161 1.85429575e-051 9.51345083e-043]]


In [5]:
# 1로 가득찬 배열
arr = np.ones((5,5))

print(arr)
#숫자 뒤에 . 이 붙어있느면 실수형

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
# 배열의 생성
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
# ndarray 배열의 모양, 차수 데이터 타입확인
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int32


In [11]:
arr_float = arr.astype(np.float64)
arr_float.dtype

dtype('float64')

In [12]:
arr_str = np.array(['1','2','3'])
arr_str.dtype

dtype('<U1')

In [13]:
arr_int = arr_str.astype(np.int64)
arr_int.dtype

dtype('int64')

In [14]:
# ndarray의 연산
 
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

In [15]:
arr1+arr2

array([[ 6,  8],
       [10, 12]])

In [16]:
np.add(arr1,arr2)

array([[ 6,  8],
       [10, 12]])

In [17]:
arr1*arr2

array([[ 5, 12],
       [21, 32]])

In [18]:
np.multiply(arr1,arr2)

array([[ 5, 12],
       [21, 32]])

In [22]:
# ndarray 배열 슬라이싱

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr.ndim

2

In [24]:
arr_1 = arr[:2,1:3]
arr_1

array([[2, 3],
       [5, 6]])

In [25]:
arr[0,2]

3

In [26]:
arr[[0,1,2],[2,0,1]]

array([3, 4, 8])

In [29]:
idx = arr > 3
idx

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [30]:
arr[idx]

array([4, 5, 6, 7, 8, 9])

In [33]:
redwine = np.loadtxt(fname='winequality-red.csv', delimiter=';', skiprows = 1)
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [34]:
# 합계
redwine.sum()

152084.78194

In [36]:
# 평균
redwine.mean()

7.926036165311652

In [37]:
# 축(axis)
redwine.sum(axis=0)

array([13303.1    ,   843.985  ,   433.29   ,  4059.55   ,   139.859  ,
       25384.     , 74302.     ,  1593.79794,  5294.47   ,  1052.38   ,
       16666.35   ,  9012.     ])

In [38]:
redwine.mean(axis=0)

array([ 8.31963727,  0.52782051,  0.27097561,  2.5388055 ,  0.08746654,
       15.87492183, 46.46779237,  0.99674668,  3.3111132 ,  0.65814884,
       10.42298311,  5.63602251])

In [40]:
redwine[:,0].mean()

8.31963727329581

In [41]:
redwine.max(axis=0)

array([ 15.9    ,   1.58   ,   1.     ,  15.5    ,   0.611  ,  72.     ,
       289.     ,   1.00369,   4.01   ,   2.     ,  14.9    ,   8.     ])

In [42]:
redwine.min(axis=0)

array([4.6    , 0.12   , 0.     , 0.9    , 0.012  , 1.     , 6.     ,
       0.99007, 2.74   , 0.33   , 8.4    , 3.     ])